
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10.15

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
    - chmod +x $CI_PROJECT_DIR/ci/setup-ssh
    - $CI_PROJECT_DIR/ci/setup-ssh github.com GITHUB_DEPLOY_KEY
    - npm config set registry ${NPM_REGISTRY}
    - curl -u $NPM_USER:$NPM_TOKEN https://bpm.jfrog.io/bpm/api/npm/auth -o .npmrc
    - npm install

test:lint:
  script:
    - npm run lint

test:
  script:
    - npm test
            
# Publish tagged versions to npm
publish:
  stage: deploy
  when: manual
  only:
    - tags
    - master
  script:
    - npm publish --registry $NPM_REGISTRY

